= Discussion

Generally speaking, modern CSS and JavaScript already provide powerful accessibility primitives, and many accessibility concerns do not require large or complex frameworks to be addressed effectively. Native capabilities are often overlooked or underestimated by developers, either due to a lack of awareness or because many modern projects begin directly with frameworks instead of first considering native approaches. In some cases, developers entering the industry are barely exposed to native environments at all, as frameworks are already introduced during apprenticeships before the fundamentals of the web platform itself are fully understood.

Frameworks certainly provide quality-of-life improvements and can simplify development in many scenarios. However, in some areas, avoiding unnecessary abstractions can reduce complexity and improve transparency. Working with native technologies and minimizing dependencies often allows for more direct customization and better adaptation to individual accessibility needs.

It is also remarkable how quickly browser standards evolve. During the timespan of this project, for example, the ``` contrast-color()``` CSS function transitioned from limited browser support to broad support across all major browsers.

At the same time, browser support for CSS and JavaScript features still contains inconsistencies. Certain areas feel incomplete or missing fundamental capabilities. However, these shortcomings should also be viewed in the context of the web platform’s continuous development, as existing gaps are gradually closed while new requirements emerge over time.

One example is the extraction of ``` RGB``` values from ``` oklch()``` colors. At the time this project was written, this was not directly possible in a practical way. A reasonable expectation would be for ``` getComputedStyle()``` to return computed ``` RGB``` values even when colors are defined using ``` oklch()```. Instead, the original ``` oklch()``` value is returned unchanged. To calculate contrast ratios, the implementation therefore had to rely on the HTML ``` <canvas>``` element to extract the required ``` RGBA``` values through ``` getImageData()```.

Another particularly interesting aspect was working with the experimental ``` @function``` at-rule. Since the feature is still experimental, incomplete behavior is expected to some extent. However, the biggest challenge was the lack of debugging possibilities combined with sparse and partially vague documentation. Developing with this feature often became a trial-and-error process because there was no reliable way to inspect intermediate states during calculations or identify why certain expressions failed. Some supported behaviors are only loosely documented, while other surprisingly useful capabilities are not documented at all despite working reliably in practice.

An additionally challenging aspect is passing relevant intermediate values into calculations. Functions such as ``` oklch()``` allow access to properties like the lightness component of a color, and these values can be manipulated directly within the function itself. However, there is currently no practical way to extract such intermediate values into custom properties for further processing. This makes it difficult to build more complex conditional logic, for example when trying to dynamically alter output values with the ``` if()``` function based on calculated lightness or other color characteristics.

The current binary pass/fail nature of the WCAG 2.x contrast requirements is another aspect worth discussing. The calculations are heavily simplified and even contain known issues, such as the threshold value ``` 0.03928``` being used instead of ``` 0.04045```, which originated from a rounding error in the original WCAG draft and later became fixed within the specification. Furthermore, the current model does not properly account for perceptual factors. A contrast ratio may technically satisfy the guideline while still appearing visually uncomfortable or less readable in practice.

This is where APCA introduces promising improvements. The model considers perceptual aspects such as text size, font weight, and surrounding context, acknowledging that readability changes depending on how content is visually presented. Once further refined and standardized, this approach could provide a far more realistic foundation for accessibility contrast evaluation across the web.

#pagebreak()